spring.application.name=Citas
spring:
datasource:
# URL de conexión (usa el pooler de Supabase para mejor rendimiento)
url: jdbc:postgresql://[HOST-DE-SUPABASE]:5432/postgres
username: postgres
password: [TU_PASSWORD_DE_SUPABASE]
driver-class-name: org.postgresql.Driver

jpa:
database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
ddl-auto: validate
show-sql: true # Útil para debuggear en el entorno de desarrollo